export { PlacaNoFormatoErradoErro } from './PlacaNoFormatoErradoErro'
export { RenavamNoFormatoErradoErro } from './RenavamNoFormatoErradoErro'
export { ModeloNoFormatoErradoErro } from './ModeloNoFormatoErradoErro'
export { MarcaNoFormatoErradoErro } from './MarcaNoFormatoErradoErro'
export { AnoNoFormatoErradoErro } from './AnoNoFormatoErradoErro'
export { ChassiNoFormatoErradoErro } from './ChassiNoFormatoErradoErro'